---
database_file: /Users/nathan/.timetrap/.timetrap.db
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
- /Users/nathan/.timetrap/formatters
- /Users/nathan/.timetrap/vendor/timetrap_formatters/formatters
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- /Users/nathan/.timetrap/auto_sheets
default_command:
auto_checkout: false
require_note: false
day_length_hours: 8
