---
- name: Install brew-cask dependencies
  homebrew_cask: name={{ item }}
  with_items:
    - iterm2
    - karabiner-elements
    - ubersicht
    - google-chrome
    - appcleaner
    - the-unarchiver
    - hammerspoon
    - alacritty
