---
- name: Change default shell to fish
  shell: chsh -s /opt/homebrew/bin/fish {{ ansible_user_id }}
  become: true

# DOCK

- name: Remove all dock items
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    value: []
    type: array
  notify:
    - restart dock

- name: Setup login items
  command: "loginitems -a '{{ item }}'"
  changed_when: false
  loop:
    - Hammerspoon
    - Karabiner-Elements

# OSX DEFAULTS:

- name: Enable full keyboard access for all controls
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    value: 3
    type: string

- name: Disable press-and-hold for accented characters
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    value: false
    type: boolean

- name: Disable pin-entry-mac (GPG tools) from storing passwords in the keychain
  community.general.osx_defaults:
    domain: org.gpgtools.common
    key: DisableKeychain
    value: true
    type: boolean

- name: Enable tap to click (com.apple.driver.AppleBluetoothMultitouch.trackpad)
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    value: 1
    type: int

- name: Enable tap to click (com.apple.AppleMultitouchTrackpad)
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    value: 1
    type: int

- name: Enable tap to click (com.apple.mouse.tapBehavior)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    value: 1
    type: int

- name: Enable natural mouse scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    value: true
    type: boolean

- name: Disable autocorrect
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    value: false
    type: boolean

- name: Unhide ~/Library
  command: chflags nohidden /Users/{{ ansible_user_id }}/Library

- name: Autohide the dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    value: true
    type: boolean
  notify:
    - restart dock

- name: Disable the downloaded app quarantine
  community.general.osx_defaults:
    domain: LSQuarantine
    key: com.apple.LaunchServices
    value: false
    type: boolean

- name: Bottom-right hotcorner locks monitor (Action)
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    value: 10
    type: int
  notify:
    - restart dock

- name: Bottom-right hotcorner locks monitor (Modifier)
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-modifier
    value: 0
    type: int
  notify:
    - restart dock

- name: Multi-list view default
  community.general.osx_defaults:
    key: FXPreferredViewStyle
    domain: com.apple.finder
    value: "clmv"
    type: string

- name: Hide desktop items
  community.general.osx_defaults:
    key: CreateDesktop
    domain: com.apple.finder
    value: 0
    type: string
  notify:
    - restart dock

- name: Require password on screensaver
  community.general.osx_defaults:
    key: askForPassword
    domain: com.apple.screensaver
    value: 1
    type: int

- name: Set screensaver password delay to 0
  community.general.osx_defaults:
    key: askForPasswordDelay
    domain: com.apple.screensaver
    value: 0
    type: float

- name: Disable expose animation
  community.general.osx_defaults:
    key: expose-animation-duration
    domain: com.apple.dock
    value: 0.1
    type: string

- name: Three finger drag (com.apple.driver.AppleBluetoothMultitouch.trackpad)
  community.general.osx_defaults:
    key: TrackpadThreeFingerDrag
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    value: 1
    type: int

- name: Three finger drag (com.apple.AppleMultitouchTrackpad)
  community.general.osx_defaults:
    key: TrackpadThreeFingerDrag
    domain: com.apple.AppleMultitouchTrackpad
    value: 1
    type: int

- name: Disable Spaces Auto Rearrange
  community.general.osx_defaults:
    key: mru-spaces
    domain: com.apple.dock
    value: false
    type: bool

- name: Don't write .DS_Store to network stores
  community.general.osx_defaults:
    key: DSDontWriteNetworkStores
    domain: com.apple.desktopservices
    value: true
    type: bool
