---

# SHELL

- name: Ensure fish is specified in /etc/shells
  become: true
  become_method: sudo
  lineinfile: line=/usr/local/bin/fish path=/etc/shells

- name: Change default shell to fish
  shell: chsh -s /usr/local/bin/fish {{ ansible_user_id }}
  become: true

# DOCK

- name: Remove all dock items
  command: dockutil --remove all
  notify:
    - restart dock


# LOGIN ITEMS:

- name: Tap loginitems repository for Homebrew
  homebrew_tap: name=OJFord/formulae state=present

- name: Install loginitems homebrew tool
  homebrew: name=loginitems state=present

- name: Setup login items
  command: "loginitems -a '{{ item }}'"
  changed_when: false
  with_items:
    - Google Drive
    - Hammerspoon
    - Karabiner-Elements
    - Übersicht

# OSX DEFAULTS:

- name: Enable full keyboard access for all controls
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    value: 3
    type: string

- name: Disable press-and-hold for accented characters
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    value: false
    type: boolean

- name: Enable tap to click (com.apple.driver.AppleBluetoothMultitouch.trackpad)
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    value: true
    type: boolean

- name: Enable tap to click (com.apple.driver.AppleBluetoothMultitouch.trackpad)
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    value: true
    type: boolean

- name: Enable tap to click (com.apple.mouse.tapBehavior)
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    value: 1
    type: int

- name: Enable natural mouse scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    value: true
    type: boolean

- name: Disable autocorrect
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    value: false
    type: boolean

- name: Unhide ~/Library
  command: chflags nohidden /Users/{{ ansible_user_id }}/Library

- name: Autohide the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    value: true
    type: boolean
  notify:
    - restart dock

- name: Disable the downloaded app quarantine
  osx_defaults:
    domain: LSQuarantine
    key: com.apple.LaunchServices
    value: false
    type: boolean

- name: Bottom-right hotcorner locks monitor (Action)
  osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    value: 10
    type: int
  notify:
    - restart dock

- name: Bottom-right hotcorner locks monitor (Modifier)
  osx_defaults:
    domain: com.apple.dock
    key: wvous-br-modifier
    value: 0
    type: int
  notify:
    - restart dock

- name: Multi-list view default
  osx_defaults:
    key: FXPreferredViewStyle
    domain: com.apple.finder
    value: 'clmv'
    type: string

- name: Hide desktop items
  osx_defaults:
    key: CreateDesktop
    domain: com.apple.finder
    value: 0
    type: string
  notify:
    - restart dock

- name: Require password on screensaver
  osx_defaults:
    key: askForPassword
    domain: com.apple.screensaver
    value: 1
    type: int

- name: Set screensaver password delay to 0
  osx_defaults:
    key: askForPasswordDelay
    domain: com.apple.screensaver
    value: 0
    type: float

- name: Disable expose animation
  osx_defaults:
    key: expose-animation-duration
    domain: com.apple.dock
    value: 0.1
    type: string

- name: Three finger drag (com.apple.driver.AppleBluetoothMultitouch.trackpad)
  osx_defaults:
    key: TrackpadThreeFingerDrag
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    value: true
    type: bool

- name: Three finger drag (com.apple.AppleMultitouchTrackpad)
  osx_defaults:
    key: TrackpadThreeFingerDrag
    domain: com.apple.AppleMultitouchTrackpad
    value: true
    type: bool

- name: Disable Spaces Auto Rearrange
  osx_defaults:
    key: mru-spaces
    domain: com.apple.dock
    value: false
    type: bool

# APPLICATION SETTINGS

- name: Update iterm2 preferences to point to the one in ~/.dotfiles
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: /Users/{{ ansible_user_id }}/.iterm2

- name: Enable iterm2 to read from the prefs folder
  osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
