---

- name: Install dnscrypt-proxy
  community.general.homebrew:
    path: /opt/homebrew/bin
    state: present
    name:
      - dnscrypt-proxy

- name: Copy over conf
  template:
    src: dnscrypt-proxy.toml.j2
    dest: /opt/homebrew/etc/dnscrypt-proxy.toml
    mode: 0600
    force: true

- name: Start the service
  command: brew services start dnscrypt-proxy

- name: Update DNS server
  command: networksetup -setdnsservers Wi-Fi 127.0.0.1 8.8.8.8 8.8.4.4
