---
- name: Check if homebrew already exists
  stat:  path=/usr/local/bin/brew
  register: homebrew_stat_result

- name: Fail if homebrew does not exist
  fail: msg="Please install homebrew first."
  when: homebrew_stat_result.stat.exists == False

- name: Clone or update password store
  git:
    dest: ~/.password-store
    repo: https://nathankot:{{ github_access_token }}@github.com/nathankot/pass.git
    update: no

- name: Clone or update .emacs.d
  git:
    dest: ~/.emacs.d
    repo: https://github.com/nathankot/dotemacs.git
    update: no

- name: Ensure the ~/Development/src directory exists
  file: path=~/Development/src state=directory

- name: Install Applications
  import_tasks: apps.yml
  tags: [apps]

- name: Install Homebrew packages
  import_tasks: packages.yml
  tags: [packages]

- name: Setup .emacs.d dependencies
  command: chdir=~/.emacs.d creates=~/.emacs.d/.cask cask install

- name: Setup configuration
  import_tasks: configuration.yml
  tags: [configuration]
