---
- name: Install homebrew packages
  homebrew: 
    state: present
    name:
      - git
      - fish
      - emacs
      - aspell
      - cask
      - coreutils
      - editorconfig
      - gnupg
      - hledger
      - httpie
      - hub
      - icdiff
      - jq
      - ledger
      - libtool
      - mcrypt
      - pass
      - pinentry-mac
      - reattach-to-user-namespace
      - spark
      - the_silver_searcher
      - tmux
      - tmux-mem-cpu-load
      - tor
      - transcrypt
      - watch
      - wget
      - x264
      - postgresql
      - mysql
      - rbenv
      - nodenv
      - node-build
      - go
      - glide
      - dockutil

- name: Install tmuxinator
  command: gem install tmuxinator
  become: true

- name: Install gocode
  command: go get -u github.com/mdempsky/gocode

- name: Install goimports
  command: go get golang.org/x/tools/cmd/goimports
