---
- name: Install homebrew packages
  homebrew:
    state: present
    name:
      - git
      - fish
      - emacs
      - aspell
      - cask
      - coreutils
      - editorconfig
      - gnupg
      - hledger
      - httpie
      - hub
      - icdiff
      - jq
      - ledger
      - libtool
      - mcrypt
      - pass
      - pinentry-mac
      - reattach-to-user-namespace
      - spark
      - the_silver_searcher
      - tmux
      - tmux-mem-cpu-load
      - tor
      - transcrypt
      - watch
      - wget
      - x264
      - postgresql
      - mysql
      - rbenv
      - pyenv
      - node
      - nodenv
      - node-build
      - go
      - glide
      - dockutil
      - carthage

- name: Install 2.5.1 to rbenv
  command: rbenv install --skip-existing 2.5.1

- name: Setup rbenv global to 2.5.1
  command: rbenv global 2.5.1

- name: Install tmuxinator
  command: gem install tmuxinator

- name: Install gocode
  command: go get -u github.com/mdempsky/gocode

- name: Install goimports
  command: go get golang.org/x/tools/cmd/goimports
