---
- name: Install homebrew packages
  community.general.homebrew:
    state: present
    name:
      - python3
      - git
      - fish
      - emacs
      - aspell
      - coreutils
      - editorconfig
      - gnupg
      - hledger
      - httpie
      - hub
      - icdiff
      - jq
      - ledger
      - libtool
      - mcrypt
      - pass
      - pinentry-mac
      - reattach-to-user-namespace
      - the_silver_searcher
      - tmux
      - tmux-mem-cpu-load
      - tor
      - transcrypt
      - watch
      - wget
      - x264
      - postgresql
      - mysql
      - node
      - dockutil
      - asdf

- name: Remove obsolete homebrew packages
  community.general.homebrew:
    state: absent
    name:
      - nodenv
      - nodebuild
      - rbenv
      - pyenv
      - glide
      - dockutil

- name: Install asdf plugins
  shell: "asdf plugin-add {{ item }}"
  creates: "~/.asdf/plugins/{{ item }}"
  loop:
    - golang
    - ruby
    - python
    - deno

- name: Install asdf plugin versions
  shell: "asdf install {{ item.name }} {{ item.version }}"
  creates: "~/.asdf/installs/{{ item.name }}/{{ item.version }}"
  loop:
    - { name: golang, version: 1.18.3 }
    - { name: golang, version: 1.17.1 }
    - { name: ruby, version: 3.1.2 }
    - { name: ruby, version: 2.7.1 }
    - { name: deno, version: 1.21.3 }

- name: Set adsf globals
  shell: "asdf global {{ item.name }} {{ item.version }}"
  loop:
    - { name: golang, version: latest }
    - { name: ruby, version: latest }
    - { name: deno, version: latest }

- name: Install go utils
  shell: "asdf exec go install {{ item }}"
  loop:
    - golang.org/x/tools/gopls@latest
    - golang.org/x/tools/cmd/goimports
    - github.com/FiloSottile/captive-browser
