---
- name: Install homebrew packages
  homebrew:
    state: present
    name:
      - git
      - fish
      - emacs
      - aspell
      - coreutils
      - editorconfig
      - gnupg
      - hledger
      - httpie
      - hub
      - icdiff
      - jq
      - ledger
      - libtool
      - mcrypt
      - pass
      - pinentry-mac
      - reattach-to-user-namespace
      - spark
      - the_silver_searcher
      - tmux
      - tmux-mem-cpu-load
      - tor
      - transcrypt
      - watch
      - wget
      - x264
      - postgresql
      - mysql
      - rbenv
      - pyenv
      - node
      - nodenv
      - node-build
      - dockutil
      - carthage
      - asdf

- name: Install 2.7.1 to rbenv
  command: rbenv install --skip-existing 2.7.1

- name: Setup rbenv global to 2.7.1
  command: rbenv global 2.7.1

- name: Add asdf golang plugin
  command: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  ignore_errors: yes

- name: Install golang version
  command: asdf install golang 1.17.1

- name: Set golang version
  command: asdf global golang 1.17.1

- name: Install tmuxinator
  command: gem install tmuxinator

- name: Install gopls
  command: asdf exec go install golang.org/x/tools/gopls@latest

- name: Install goimports
  command: asdf exec go install golang.org/x/tools/cmd/goimports

- name: Install captive browser
  command: asdf exec go install github.com/FiloSottile/captive-browser
