#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/TAGS.$$" EXIT

# Tell ctags to go through all the git ls-files
git ls-files -cd | ctags -e \
                         -L - \
                         --tag-relative \
                         --exclude=*.min.js \
                         --exclude=*.min.css \
                         --exclude=*.min.* \
                         --exclude=vendor \
                         --exclude=components \
                         --exclude=component \
                         --exclude=bower_components \
                         --languages=-html \
                         -R \
                         -f.git/TAGS.$$

mv .git/TAGS.$$ .git/TAGS
