#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/TAGS.$$" EXIT

# Tell ctags to go through all the git ls-files
git ls-files -cd | etags -L - --tag-relative -Rf.git/TAGS.$$
mv .git/TAGS.$$ .git/TAGS
