set fish_greeting "Let's go."
set -x FISH_CLIPBOARD_CMD pbcopy
set -x TERM screen-256color
set -x GITHUB_USER nathankot

### This stuff is generated by Boxen, but they don't support
### fish so it's c&p'd here manually.
#############################################################
set -x BOXEN_HOME /opt/boxen
set -x BOXEN_GITHUB_LOGIN $GITHUB_USER
set -x HOMEBREW_ROOT /opt/boxen/homebrew
set -x HOMEBREW_CACHE /opt/boxen/cache/homebrew
set -x CFLAGS "-I$HOMEBREW_ROOT/include"
set -x LDFLAGS "-L$HOMEBREW_ROOT/lib"

# Add homebrew'd stuff to the path.
set -x PATH $BOXEN_HOME/homebrew/bin $BOXEN_HOME/homebrew/sbin $PATH
set -x MANPATH $BOXEN_HOME/homebrew/share/man $MANPATH
set -x PATH $BOXEN_HOME/bin $PATH

# Emacs
if command -v emacs > /dev/null
  set -x EDITOR "emacsclient -a '' -t"
  set -x ALTERNATIVE_EDITOR emacs # fallback to vanilla
end

# Ledger
if command -v ledger > /dev/null
set -x LEDGER_BASE_CURRENCY NZD
end

# Heroku
if command -v heroku > /dev/null
  set -x PATH $BOXEN_HOME/heroku/bin $PATH
end

# PHP
if test -d ~/.phpenv
  set -x PHPENV_ROOT ~/.phpenv
  set -x PATH ~/.phpenv/shims ~/.phpenv/bin ~/.phpenv/plugins/php-build/bin $PATH
  phpenv rehash >/dev/null ^&1
end

# NODE
if command -v nodenv > /dev/null
  set -x NODENV_ROOT $BOXEN_HOME/nodenv
  set -x PATH $BOXEN_HOME/nodenv/shims $BOXEN_HOME/nodenv/bin $PATH
  set -x PATH node_modules/.bin $PATH
  nodenv rehash >/dev/null ^&1
end

# RUBY
if command -v rbenv > /dev/null
  set -x PATH $BOXEN_HOME/ruby-build/bin $PATH
  set -x RBENV_ROOT /opt/boxen/rbenv
  set -x PATH $RBENV_ROOT/shims $RBENV_ROOT/bin $PATH
  rbenv rehash >/dev/null ^&1
end

# MONGODB
if command -v mongodb > /dev/null
  set -x BOXEN_MONGODB_HOST 127.0.0.1
  set -x BOXEN_MONGODB_PORT 27017
  set -x BOXEN_MONGODB_URL mongodb://$BOXEN_MONGODB_HOST:$BOXEN_MONGODB_PORT/
end

# Virtualenv
if command -v virtualenv > /dev/null
  set -x PATH ./env/bin $PATH
end

# Haskell
if command -v stack > /dev/null
  set -x PATH $HOME/.local/bin $PATH
end

# GO
if command -v go > /dev/null
  set -x GOPATH $HOME/Development
  set -x PATH $GOPATH/bin $PATH
end

# Home bin
set -x PATH $HOME/bin $PATH
set -x PATH $HOME/.bin $PATH
# ./bin should take precedence
set -x PATH ./.bin $PATH
set -x PATH ./bin $PATH

# Browser testing
set -x CHROME_BIN /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

# Ledger
set -x LEDGER ~/Documents/Personal/Accounts/current.ledger
set -x LEDGER_PRICE_DB ~/Documents/Personal/Accounts/prices.db
