---
- name: Install homebrew packages
  community.general.homebrew:
    state: present
    path: /opt/homebrew/bin
    name:
      - python@3.10
      - git
      - fish
      - emacs
      - aspell
      - coreutils
      - editorconfig
      - gnupg
      - hledger
      - httpie
      - icdiff
      - jq
      - ledger
      - libtool
      - netcat
      - pass
      - pinentry-mac
      - reattach-to-user-namespace
      - the_silver_searcher
      - tmux
      - tmux-mem-cpu-load
      - tor
      - transcrypt
      - watch
      - wget
      - x264
      - postgresql
      - mysql
      - node
      - dockutil
      - asdf
      - freetype
      - qmk/qmk/qmk

- name: Remove obsolete homebrew packages
  community.general.homebrew:
    state: absent
    path: /opt/homebrew/bin
    name:
      - nodenv
      - node-build
      - rbenv
      - ruby-build
      - pyenv
      - glide
      - dockutil

- name: Install asdf plugins and latest known versions
  shell:
    cmd: |
      asdf plugin-add {{ item.name }}
      asdf install {{ item.name }} {{ item.version }}
      asdf global {{ item.name }} {{ item.version }}
    creates: "~/.asdf/installs/{{ item.name }}/{{ item.version }}"
  loop:
    - { name: golang, version: 1.18.3 }
    - { name: ruby, version: 3.1.2 }
    - { name: deno, version: 1.21.3 }
    - { name: nodejs, version: 18.5.0 }

- name: Install go utils
  shell:
    cmd: "asdf exec go get -u {{ item.url }}"
    creates: "~/Development/bin/{{ item.bin }}"
  loop:
    - url: golang.org/x/tools/gopls@latest
      bin: gopls
    - url: golang.org/x/tools/cmd/goimports
      bin: goimports
    - url: github.com/FiloSottile/captive-browser
      bin: captive-browser
